### ISSUE TITLE
Nvidia - Request for more memory than is available on the system.

### ISSUE THREAD

**Issue by mateon1** [thatapplefreak/VoxelCam#15]
I am trying to take huge screenshots (IMAX resolution), but Minecraft keeps crashing, regardless if I take the screenshot with the HUD overlay on or off.

I think this mod is trying to render a single massive frame all at once, and my GPU doesn't have that much memory to render all that. I believe there was another mod that allowed taking massive screenshots that had the option to render the giant screenshot in tiles, combining them after all smaller screenshots were taken.

Would it be possible to add tiled screenshots into this mod?

**Comment by thatapplefreak** [comment]
how much memory does your gpu have exactly and how much of the systems ram have you allocated to minecraft?
