### ISSUE TITLE
Don't reinvent the wheel. (Translations)

### ISSUE THREAD

**Issue by mattmess1221** [thatapplefreak/VoxelCam#7]
You don't need to write your own code to translate stuff.  Minecraft has this built-in already and should automatically register it.  Just put your lang files in /assest/voxelcam/lang/ and call `net.minecraft.util.I18n.format(String)` and it will return the translated string.

**Comment by Mumfrey** [comment]
It's okay I already mentioned that.

**Comment by thatapplefreak** [comment]
Taken care of
